"""sessions and messages

Phase 2B: conversation state only. Transcript/chunk/artifact tables arrive in
Phases 3 and 7. Hand-written rather than autogenerated so the schema is
reviewable and deterministic.

Revision ID: 0001
Revises:
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto on older servers; on PG13+ it is
    # built in. IDs are generated application-side anyway, so this is only a
    # safety net for manual inserts.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("title", sa.String(200), nullable=True),
        sa.Column("user_metadata", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("provider", sa.String(32), nullable=False),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )
    op.create_index("ix_sessions_created_at", "sessions", ["created_at"])

    op.create_table(
        "messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        # NOT NULL + CASCADE: a message cannot exist outside a session, and
        # deleting a session cannot orphan one. Session isolation is
        # structural, not merely enforced in application code.
        sa.Column("session_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("sessions.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(32), nullable=True),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.CheckConstraint("role IN ('user','assistant','system')",
                           name="ck_messages_role"),
    )
    op.create_index("ix_messages_session_id", "messages", ["session_id"])
    # UNIQUE(session_id, seq): ordering is well-defined and a duplicate
    # sequence number inside one session is impossible.
    op.create_index("ix_messages_session_seq", "messages",
                    ["session_id", "seq"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_messages_session_seq", table_name="messages")
    op.drop_index("ix_messages_session_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_sessions_created_at", table_name="sessions")
    op.drop_table("sessions")
