"""transcripts and chunks

Phase 3: the knowledge base. Hand-written rather than autogenerated so the
schema is reviewable and deterministic, matching 0001.

Two choices here are load-bearing and worth reading twice:

  1. `embedding vector` is declared WITHOUT a dimension. OD-1 locks exact
     search with no ANN index, and only an index requires a fixed width. So
     switching embedding model (all-minilm 384 -> nomic-embed-text 768) is an
     env change plus a re-ingest, never a migration. Verified against the live
     server: one dimensionless column stored 3-wide and 384-wide vectors side
     by side.

  2. Because of (1) the DATABASE CANNOT detect a mixed vector space. That is
     precisely why embedding_model/embedding_dim are stored on both tables and
     enforced in application code at query time.

Revision ID: 0002
Revises: 0001
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "transcripts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        # source_id in the skill-02 contract; also the manifest key and the
        # on-disk filename. One identifier end to end.
        sa.Column("slug", sa.String(160), nullable=False, unique=True),
        sa.Column("guest", sa.String(200), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("youtube_url", sa.Text(), nullable=False),
        sa.Column("video_id", sa.String(32), nullable=False),
        sa.Column("publish_date", sa.Date(), nullable=True),
        sa.Column("channel", sa.String(120), nullable=False, server_default=""),
        sa.Column("keywords", postgresql.JSONB(), nullable=False,
                  server_default=sa.text("'[]'::jsonb")),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(64), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        # The Phase 1 silent-drop defect, made unrepresentable in the schema.
        sa.CheckConstraint("turn_count > 0", name="ck_transcripts_turn_count"),
        sa.CheckConstraint("embedding_dim > 0",
                           name="ck_transcripts_embedding_dim"),
    )
    op.create_index("ix_transcripts_content_hash", "transcripts", ["content_hash"])

    op.create_table(
        "chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("transcript_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("transcripts.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(200), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_seconds", sa.Integer(), nullable=False),
        sa.Column("end_seconds", sa.Integer(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=False),
        # No dimension. See the module docstring.
        sa.Column("embedding", Vector(), nullable=False),
        sa.Column("embedding_model", sa.String(64), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.UniqueConstraint("transcript_id", "chunk_index",
                            name="uq_chunks_transcript_index"),
        sa.CheckConstraint("end_seconds >= start_seconds",
                           name="ck_chunks_time_order"),
        sa.CheckConstraint("start_seconds >= 0", name="ck_chunks_start_nonneg"),
    )
    op.create_index("ix_chunks_transcript_id", "chunks", ["transcript_id"])

    # Deliberately NO HNSW/IVFFlat index. At ~1,400 chunks an exact sequential
    # scan gives 100% recall by construction in low single-digit milliseconds,
    # against a 25-620s generation step. An ANN index would trade recall away
    # for latency we do not need. Adding one later is a one-line change.


def downgrade() -> None:
    op.drop_index("ix_chunks_transcript_id", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_transcripts_content_hash", table_name="transcripts")
    op.drop_table("transcripts")
